BASE:
  CONCURRENCY: 1
  MAX_MEMORY: 1024
  NAME: TEST_MERCADOLIBRE
  LOGGER:
    LEVEL: debug


APP:
  PORT: 3000
  HOST: 0.0.0.0

  CHUNK_TYPES: development

  API:
    MAX_RETRIES: 1
    TIMEOUT: 15000
    BASE_URL: 'https://api.mercadolibre.com/'
